package auroracafe.ui;

import auroracafe.model.User;
import auroracafe.service.AuthService;
import auroracafe.util.LuxuryLoginHeroPanel;
import auroracafe.util.RoundBorder;
import auroracafe.util.RoundButton;
import auroracafe.util.UiTheme;
import java.awt.*;
import javax.swing.*;

public class LoginFrame extends JFrame {
    private final AuthService authService;
    private final LoginSuccessHandler successHandler;
    private final CardLayout authCards = new CardLayout();
    private final JPanel authPanel = new JPanel(authCards);
    private JTextField txtUsername; private JPasswordField txtPassword; private JTextField txtRegisterName; private JTextField txtRegisterUsername; private JPasswordField txtRegisterPassword; private JPasswordField txtRegisterConfirm;
    public interface LoginSuccessHandler { void onLogin(User user); }
    public LoginFrame(AuthService authService, LoginSuccessHandler successHandler) { this.authService = authService; this.successHandler = successHandler; initUi(); }
    private void initUi() {
        setTitle("KIỆT NAM CAFÉ LUXURY - Xin chào!!"); setSize(1680, 980); setLocationRelativeTo(null); setDefaultCloseOperation(EXIT_ON_CLOSE); setLayout(new BorderLayout()); getContentPane().setBackground(new Color(248, 244, 236));
        JPanel left = new JPanel(new BorderLayout()); left.setPreferredSize(new Dimension(790, 0)); left.setBorder(BorderFactory.createEmptyBorder(16, 18, 16, 12)); left.setOpaque(false); left.add(new LuxuryLoginHeroPanel(), BorderLayout.CENTER);
        JPanel rightWrapper = new RightDecorPanel(); rightWrapper.setLayout(new GridBagLayout()); rightWrapper.setBorder(BorderFactory.createEmptyBorder(28, 20, 28, 24));
        JPanel glassCard = new JPanel(new BorderLayout()); glassCard.setPreferredSize(new Dimension(710, 780)); glassCard.setOpaque(false); glassCard.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(233, 216, 190), 2), BorderFactory.createEmptyBorder(2, 2, 2, 2)), BorderFactory.createEmptyBorder(38, 56, 34, 56))); glassCard = new RoundedSurfacePanel(glassCard);
        JPanel top = new JPanel(); top.setOpaque(false); top.setLayout(new BoxLayout(top, BoxLayout.Y_AXIS)); JLabel bean = new JLabel("●", SwingConstants.CENTER); bean.setForeground(new Color(210, 158, 71)); bean.setFont(new Font("Dialog", Font.BOLD, 28)); bean.setAlignmentX(Component.CENTER_ALIGNMENT); JLabel title = new JLabel("KIỆT NAM CAFÉ LUXURY", SwingConstants.CENTER); title.setFont(new Font("Serif", Font.BOLD, 38)); title.setForeground(new Color(56, 34, 21)); title.setAlignmentX(Component.CENTER_ALIGNMENT); JLabel desc = new JLabel("Chào mừng bạn đến với hệ thống quản lý quán cà phê!", SwingConstants.CENTER); desc.setFont(new Font("Segoe UI", Font.PLAIN, 18)); desc.setForeground(UiTheme.MUTED); desc.setAlignmentX(Component.CENTER_ALIGNMENT); top.add(bean); top.add(Box.createVerticalStrut(4)); top.add(title); top.add(Box.createVerticalStrut(12)); top.add(desc); top.add(Box.createVerticalStrut(26)); glassCard.add(top, BorderLayout.NORTH);
        authPanel.setOpaque(false); authPanel.add(createLoginForm(), "login"); authPanel.add(createRegisterForm(), "register"); glassCard.add(authPanel, BorderLayout.CENTER); rightWrapper.add(glassCard);
        add(left, BorderLayout.WEST); add(rightWrapper, BorderLayout.CENTER);
    }
    private JPanel createLoginForm() { JPanel panel=formPanel(); GridBagConstraints gbc=baseGbc(); panel.add(sectionTitle("Đăng nhập tài khoản nhân viên"),gbc); gbc.gridy++; panel.add(helpLabel("Tên đăng nhập"),gbc); gbc.gridy++; txtUsername=new JTextField(); styleField(txtUsername); panel.add(txtUsername,gbc); gbc.gridy++; panel.add(helpLabel("Mật khẩu"),gbc); gbc.gridy++; txtPassword=new JPasswordField(); styleField(txtPassword); panel.add(wrapPasswordField(txtPassword),gbc); gbc.gridy++; gbc.insets=new Insets(20,0,12,0); JButton btnLogin=primaryButton("Đăng nhập ngay"); btnLogin.addActionListener(e->doLogin()); panel.add(btnLogin,gbc); gbc.gridy++; gbc.insets=new Insets(8,0,8,0); JLabel tip=helpLabel("Luôn có biểu tượng con mắt để xem hoặc ẩn mật khẩu."); tip.setHorizontalAlignment(SwingConstants.CENTER); panel.add(tip,gbc); gbc.gridy++; panel.add(linkButton("Chưa có tài khoản? Tạo tài khoản mới",()->authCards.show(authPanel,"register")),gbc); return panel; }
    private JPanel createRegisterForm() { JPanel panel=formPanel(); GridBagConstraints gbc=baseGbc(); panel.add(sectionTitle("Tạo tài khoản mới"),gbc); gbc.gridy++; panel.add(helpLabel("Tên người dùng / Họ và tên"),gbc); gbc.gridy++; txtRegisterName=new JTextField(); styleField(txtRegisterName); panel.add(txtRegisterName,gbc); gbc.gridy++; panel.add(helpLabel("Tên đăng nhập"),gbc); gbc.gridy++; txtRegisterUsername=new JTextField(); styleField(txtRegisterUsername); panel.add(txtRegisterUsername,gbc); gbc.gridy++; panel.add(helpLabel("Mật khẩu"),gbc); gbc.gridy++; txtRegisterPassword=new JPasswordField(); styleField(txtRegisterPassword); panel.add(wrapPasswordField(txtRegisterPassword),gbc); gbc.gridy++; panel.add(helpLabel("Nhập lại mật khẩu"),gbc); gbc.gridy++; txtRegisterConfirm=new JPasswordField(); styleField(txtRegisterConfirm); panel.add(wrapPasswordField(txtRegisterConfirm),gbc); gbc.gridy++; gbc.insets=new Insets(20,0,12,0); JButton btnRegister=primaryButton("Đăng ký tài khoản"); btnRegister.addActionListener(e->doRegister()); panel.add(btnRegister,gbc); gbc.gridy++; gbc.insets=new Insets(8,0,8,0); panel.add(linkButton("Đã có tài khoản? Quay về đăng nhập",()->authCards.show(authPanel,"login")),gbc); return panel; }
    private JPanel wrapPasswordField(JPasswordField field){ JPanel wrapper=new JPanel(new BorderLayout(10,0)); wrapper.setOpaque(false); wrapper.add(field,BorderLayout.CENTER); JButton eye=new JButton("👁"); eye.setFocusPainted(false); eye.setBorder(new RoundBorder(18,new Color(222,199,159))); eye.setBackground(new Color(255,252,248)); eye.setFont(new Font("Segoe UI Emoji",Font.PLAIN,18)); eye.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); eye.setPreferredSize(new Dimension(60,56)); final char def=field.getEchoChar(); eye.addActionListener(e->{ if(field.getEchoChar()==(char)0){ field.setEchoChar(def); eye.setText("👁"); } else { field.setEchoChar((char)0); eye.setText("🙈"); }}); wrapper.add(eye,BorderLayout.EAST); return wrapper; }
    private JPanel formPanel(){ JPanel p=new JPanel(new GridBagLayout()); p.setOpaque(false); return p; }
    private GridBagConstraints baseGbc(){ GridBagConstraints gbc=new GridBagConstraints(); gbc.gridx=0; gbc.gridy=0; gbc.fill=GridBagConstraints.HORIZONTAL; gbc.weightx=1; gbc.insets=new Insets(10,0,10,0); return gbc; }
    private JLabel sectionTitle(String text){ JLabel l=new JLabel(text,SwingConstants.CENTER); l.setFont(new Font("Serif",Font.BOLD,28)); l.setForeground(UiTheme.TEXT); return l; }
    private JLabel helpLabel(String text){ JLabel l=new JLabel(text); l.setFont(new Font("Segoe UI",Font.PLAIN,16)); l.setForeground(UiTheme.MUTED); return l; }
    private JButton linkButton(String text,Runnable action){ JButton b=new JButton(text); b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); b.setBorderPainted(false); b.setContentAreaFilled(false); b.setFocusPainted(false); b.setForeground(new Color(181,137,70)); b.setFont(new Font("Serif",Font.BOLD,15)); b.setHorizontalAlignment(SwingConstants.CENTER); b.addActionListener(e->action.run()); return b; }
    private void doLogin(){ User user=authService.login(txtUsername.getText().trim(), new String(txtPassword.getPassword())); if(user==null){ JOptionPane.showMessageDialog(this,"Sai tài khoản hoặc mật khẩu.","Đăng nhập thất bại",JOptionPane.ERROR_MESSAGE); return;} dispose(); SwingUtilities.invokeLater(()->successHandler.onLogin(user)); }
    private void doRegister(){ String error=authService.registerPublic(txtRegisterName.getText().trim(),txtRegisterUsername.getText().trim(),new String(txtRegisterPassword.getPassword()),new String(txtRegisterConfirm.getPassword())); if(error!=null){ JOptionPane.showMessageDialog(this,error,"Đăng ký thất bại",JOptionPane.ERROR_MESSAGE); return;} JOptionPane.showMessageDialog(this,"Đăng ký thành công. Bạn có thể đăng nhập ngay bây giờ.","Thành công",JOptionPane.INFORMATION_MESSAGE); txtUsername.setText(""); txtPassword.setText(""); txtRegisterName.setText(""); txtRegisterUsername.setText(""); txtRegisterPassword.setText(""); txtRegisterConfirm.setText(""); authCards.show(authPanel,"login"); }
    private void styleField(JTextField field){ field.setFont(new Font("Segoe UI",Font.PLAIN,16)); field.setBackground(new Color(255,252,248)); field.setBorder(new RoundBorder(18,new Color(222,199,159))); field.setPreferredSize(new Dimension(470,56)); }
    private JButton primaryButton(String text){ RoundButton b=new RoundButton(text,UiTheme.PRIMARY,new Color(139,91,59),new Color(97,57,30)); b.setForeground(new Color(247,219,145)); b.setFont(new Font("Serif",Font.BOLD,18)); b.setPreferredSize(new Dimension(470,58)); return b; }
    private static class RoundedSurfacePanel extends JPanel { RoundedSurfacePanel(JPanel content){ super(new BorderLayout()); setOpaque(false); add(content,BorderLayout.CENTER);} @Override protected void paintComponent(Graphics g){ Graphics2D g2=(Graphics2D)g.create(); g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON); g2.setPaint(new GradientPaint(0,0,new Color(255,255,253),0,getHeight(),new Color(252,247,239))); g2.fillRoundRect(0,0,getWidth(),getHeight(),34,34); g2.setColor(new Color(231,216,194)); g2.drawRoundRect(0,0,getWidth()-1,getHeight()-1,34,34); g2.dispose(); super.paintComponent(g);} }
    private static class RightDecorPanel extends JPanel { RightDecorPanel(){ setOpaque(false);} @Override protected void paintComponent(Graphics g){ super.paintComponent(g); Graphics2D g2=(Graphics2D)g.create(); g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON); g2.setColor(new Color(227,208,180)); g2.setStroke(new BasicStroke(2f)); for(int i=0;i<6;i++){ g2.drawOval(getWidth()-190+i*8,80+i*26,56,86); g2.drawOval(getWidth()-92+i*6,400+i*24,48,72);} for(int i=0;i<7;i++) g2.fillOval(getWidth()-118+(i%3)*18,430+i*32,12,12); g2.dispose(); } }
}
